version: "3.8"

services:
  sector:
    build:
      context: .
      dockerfile: ./sector/Dockerfile
    container_name: sector-soh
    command: ["./sector_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  drone:
    build:
      context: .
      dockerfile: ./drone/Dockerfile
    container_name: drone-soh
    command: ["./drone_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  sensor:
    build:
      context: .
      dockerfile: ./sensor/Dockerfile
    container_name: sensor-soh
    command: ["./sensor_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  interface-server:
    build:
      context: .
      dockerfile: ./interface/Dockerfile.go
    container_name: interface-soh
    command: ["./interface_bin"]
    volumes:
      - ./data:/app/data

  interface-gui:
    build:
      context: .
      dockerfile: ./interface/Dockerfile.py
    container_name: interface-gui-soh
    command: ["python3", "interface.py"]
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/app/data
