version: "3.8"

services:
  sector:
    build:
      context: ./sector
      dockerfile: Dockerfile
    command: ["./sector_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  drone:
    build:
      context: ./drone
      dockerfile: Dockerfile
    command: ["./drone_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  sensor:
    build:
      context: ./sensor
      dockerfile: Dockerfile
    command: ["./sensor_bin", "${ID}"]
    volumes:
      - ./data:/app/data

  interface-server:
    build:
      context: ./interface
      dockerfile: Dockerfile.go
    command: ["./interface_bin"]
    volumes:
      - ./data:/app/data

  interface-gui:
    build:
      context: ./interface
      dockerfile: Dockerfile.py
    command: ["python3", "interface.py"]
    volumes:
      - ./data:/app/data